### ISSUE TITLE
warning: The preprocessor macro `STDC_HEADERS' is obsolete.

### ISSUE THREAD

**Issue by jonasstein** [scsitape/stenc#105]
```
autoreconf --install
configure.ac:15: warning: The preprocessor macro `STDC_HEADERS' is obsolete.
configure.ac:15:   Except in unusual embedded environments, you can safely include all
configure.ac:15:   ISO C90 headers unconditionally.
```

**Comment by jmwilson** [comment]
This is printed explicitly from `configure.ac`
https://github.com/scsitape/stenc/commit/aa2244308dc947bce16b5ad1e4a528a21553bdcc#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R12-R15

Was this some kind of update tool that rewrote part of the file?
