### ISSUE TITLE
LTO-9 density code not mapped

### ISSUE THREAD

**Issue by linkinpark9812** [scsitape/stenc#113]
My HP LTO-9 drive has a density code of 0x60 when a standard LTO-9 tape is inserted, but no translation shows up as the text. It should state "LTO-9"

![image](https://github.com/scsitape/stenc/assets/30772334/6c379efc-8b30-4748-a9cb-a60d84cb9438)

**Comment by jonasstein** [comment]
@linkinpark9812 Why did you close this? Does it work for you now? Could you test it with the latest source?

**Comment by linkinpark9812** [comment]
> @linkinpark9812 Why did you close this? Does it work for you now? Could you test it with the latest source?

I closed this because I opened this for the wrong repository. This was the issue I opened for the correct repository: https://github.com/iustin/mt-st/issues/26

**Comment by jonasstein** [comment]
Thank you for the fast reply and the explanation.
