### ISSUE TITLE
stenc: Package for Red Hat / CentOS / Fedora

### ISSUE THREAD

**Issue by devnullzero** [scsitape/stenc#13]
stenc should be included in Red Hat / CentOS / Fedora

Red Hat: The code path - How does new code enter Red Hat products?
https://www.redhat.com/en/blog/code-path-how-does-new-code-enter-red-hat-products

Fedora project: Package Review Process
https://fedoraproject.org/wiki/Package_Review_Process

**Comment by jonasstein** [comment]
I fully support this, but it should be reported at the distros, not here (upstream). 
https://repology.org/project/stenc/versions
Closing.
