### ISSUE TITLE
Release 1.0.9

### ISSUE THREAD

**Issue by sunwire** [scsitape/stenc#33]
I think it should be 1.0.9
https://github.com/scsitape/stenc/blob/35b852cfeb3d405fbfe22e71cf48b0bc8ab4b01b/configure.ac#L1

https://github.com/scsitape/stenc/blob/35b852cfeb3d405fbfe22e71cf48b0bc8ab4b01b/configure.ac#L18
This macro requires autoconf at least version 2.70. Many systems use version 2.69 e.g Fedora 35, CentOS 8 and 9, Ubuntu 20.04.
It compiles without this macro just fine, so it should be removed.

Also the ChangeLog file should be updated.

**Comment by jonasstein** [comment]
thanks I was searching for the bug...

**Comment by jonasstein** [comment]
fixed with https://github.com/scsitape/stenc/commit/8ff2e4c4ebace927668f1aafc537c79dafbee8e1 Thanks
